# Generated by Django 2.2.7 on 2019-12-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('publish', models.BooleanField()),
                ('index', models.BooleanField()),
                ('create_at', models.DateTimeField()),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
