# Generated by Django 2.2.7 on 2019-12-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.ImageField(upload_to=''),
        ),
    ]
