# Generated by Django 2.2.7 on 2019-12-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_auto_20191210_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='path',
            field=models.TextField(),
        ),
    ]
