# Generated by Django 2.2.7 on 2019-12-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
