# Generated by Django 2.2.7 on 2019-12-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20191209_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='update_at',
            field=models.DateTimeField(null=True),
        ),
    ]
