# Generated by Django 2.2.7 on 2019-12-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191209_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workskill',
            old_name='content',
            new_name='skill',
        ),
    ]
