# Generated by Django 2.2.7 on 2019-11-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
