# Generated by Django 2.2.7 on 2019-12-19 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='Message_id',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='replies',
            old_name='User_id',
            new_name='User',
        ),
    ]
