# Generated by Django 2.2.7 on 2019-12-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20191219_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reply_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
