# Generated by Django 2.2.7 on 2019-12-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_messages_reply_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='User_id',
            new_name='User',
        ),
    ]
