# Generated by Django 2.2.7 on 2019-11-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['price']},
        ),
    ]
