# Generated by Django 2.2.7 on 2019-11-29 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='comment',
        ),
    ]
